import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import NavBar from "@/components/NavBar/NavBar";
import { Toaster } from "@/components/ui/sonner";
import { PlayerStoreProvider } from "@/store/player-store";
import { PlaylistProvider } from "@/store/playlist-store";
import BottomBar from "@/components/BottomBar/BottomBar";
import { AudioEngine } from "@/components/AudioEngine/AudioEngine";
import SideBar from "@/components/SideBar/SideBar";

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto",
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
};

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={roboto.variable}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NextIntlClientProvider>
                    <div className="bg-background flex h-screen w-full flex-1 flex-col overflow-hidden">
                        <NavBar />
                        <PlaylistProvider>
                            <PlayerStoreProvider>
                                <div className="flex gap-x-2 overflow-hidden">
                                    <SideBar></SideBar>
                                    <main className="flex flex-1 overflow-y-auto">{children}</main>
                                </div>
                                <AudioEngine />
                                <BottomBar />
                            </PlayerStoreProvider>
                        </PlaylistProvider>
                        <Toaster />
                    </div>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
