import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "@/theme/theme ";
import NavBar from "@/ui/NavBar";
import { Box } from "@mui/material";
import { NextIntlClientProvider } from "next-intl";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <NextIntlClientProvider>
                <Box sx={{display:"flex", flexDirection:"column", gap:2, justifyContent:"center", alignItems:"center"}}>
                  <NavBar />
                  {children}
                </Box>
              </NextIntlClientProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
